[book]
authors = ["Zoom.Quiet <zoomquiet+io@gmail.com>"]
language = "zh"
multilingual = false
src = "src"
title = "ZoomQuiet.io"

[preprocessor.pagetoc]

[output.html]
pagetoc = true
sidebar-width = "250px"
default-theme = "light"
git-repository-url = "https://github.com/zoom-quiet/io"
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]
include-after = ["./src/images"]
no-section-label = true

[output.html.fold]
enable = true
level = 4

[output.html.playground]
editable = true

[output.html.print]
enable = false

