[book]
authors = ["Zoom.Quiet <zoomquiet+io@gmail.com>"]
language = "zh"
multilingual = false
src = "src"
title = "ZoomQuiet.io"

[preprocessor.pagetoc]
command = "mdbook-pagetoc"
optional = true

[preprocessor.theme]
command = "mdbook-theme"
optional = true
pagetoc = true
sidebar-width = "250px"

[output.theme-ace]
optional = true
theme-white = "xcode"
theme-dark = "monokai"

[output.html]
default-theme = "light"
git-repository-url = "https://github.com/zoom-quiet/io"
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]
include-after = ["./src/images"]
no-section-label = true

[output.html.fold]
enable = true
level = 2

[output.html.playground]
editable = true

[output.html.print]
enable = false

