name: Mdbook build

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      MDBOOK_VERSION: '0.4.12'
      MDBOOK_LINKCHECK_VERSION: '0.7.4'
      MDBOOK_MERMAID_VERSION: '0.8.3'
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install mdbook
      run: |
        mkdir ~/tools
        curl -L https://github.com/rust-lang/mdBook/releases/download/v$MDBOOK_VERSION/mdbook-v$MDBOOK_VERSION-x86_64-unknown-linux-gnu.tar.gz | tar xz -C ~/tools
        curl -L https://github.com/badboy/mdbook-mermaid/releases/download/v$MDBOOK_MERMAID_VERSION/mdbook-mermaid-v$MDBOOK_MERMAID_VERSION-x86_64-unknown-linux-gnu.tar.gz | tar xz -C ~/tools
        curl -L https://github.com/Michael-F-Bryan/mdbook-linkcheck/releases/download/v$MDBOOK_LINKCHECK_VERSION/mdbook-linkcheck.v$MDBOOK_LINKCHECK_VERSION.x86_64-unknown-linux-gnu.zip -O
        unzip mdbook-linkcheck.v$MDBOOK_LINKCHECK_VERSION.x86_64-unknown-linux-gnu.zip -d ~/tools
        chmod +x ~/tools/mdbook-linkcheck
        curl -s https://api.github.com/repos/zjp-CN/mdbook-theme/releases/latest \
               | grep browser_download_url \
               | grep mdbook-theme_linux \
               | cut -d '"' -f 4 \
               | wget -qi -
        tar -xzf mdbook-theme_linux.tar.gz -C ~/tools
        echo ~/tools >> $GITHUB_PATH
    #- name: Build
    #  run: mdbook build

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build mdbook
      run: |
        mdbook build || exit 1
        echo "Mdbook build finished."
      #run: mdbook build

    - name: Generate RSS feed
      run: |
        inv gen || exit 1
        echo "RSS feed generation finished."

    - name: Check generated files
      run: |
        echo "Listing generated files in book/"
        ls -al book/
        echo "Checking if rss.xml exists"
        ls -al rss.xml

    # share between different jobs
    - uses: actions/upload-artifact@v4
      with:
        name: book-and-rss
        path: |
          book/
          rss.xml
          CNAME
          .nojekyll
        #path: book/
